[package]
name = 'actix-web'
version = '0.1.0'
edition = '2021'

[dependencies]
actix-web = '4'

[dependencies.tokio]
version = '1.22'
features = [
    'rt',
    'rt-multi-thread',
    'io-util',
    'macros',
]
